"""
HTML formatter for standalone GEO audit reports.

Generates a self-contained HTML file with embedded CSS, openable directly in the
browser. Used with ``geo audit --format html``.

The HTML report renders the COMPLETE audit — every section and line that the
text report shows — so it is a true downloadable deliverable for a developer,
not a summary. It does this by rendering ``format_audit_text`` (the single
source of truth for the full report) into styled, colored section cards.
"""

from __future__ import annotations

from datetime import datetime, timezone

from geo_optimizer.models.results import AuditResult

_BAND_COLORS = {
    "excellent": "#34D399",
    "good": "#22D3EE",
    "foundation": "#FBBF24",
    "critical": "#F87171",
}
_BAND_LABELS = {
    "excellent": "EXCELLENT",
    "good": "GOOD",
    "foundation": "FOUNDATION",
    "critical": "CRITICAL",
}

_DIVIDER = "=" * 60


def format_audit_html(result: AuditResult) -> str:
    """Generate a standalone, COMPLETE HTML report with embedded CSS.

    Renders the full text report (all 19 sections + final score + priority
    steps) as styled section cards — nothing is summarised away.
    """
    # Import here to avoid any import-order coupling between formatters.
    from geo_optimizer.cli.formatters import format_audit_text

    color = _BAND_COLORS.get(result.band, "#A78BFA")
    band_label = _BAND_LABELS.get(result.band, result.band.upper())

    full_text = format_audit_text(result)
    sections_html = _render_sections(full_text)

    status_bits = [f"HTTP {result.http_status}", f"{result.page_size:,} bytes"]
    if result.audit_duration_ms is not None:
        status_bits.append(f"{result.audit_duration_ms} ms")
    status_line = " · ".join(status_bits)

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>GEO Technical Report — {_escape(result.url)}</title>
<style>
*{{margin:0;padding:0;box-sizing:border-box}}
:root{{--bg:#0A0A12;--surface:#16161F;--surface2:#1C1C28;--border:rgba(255,255,255,.07);
--text:#E4E4E7;--muted:#A1A1AA;--accent:#A78BFA;--green:#34D399;--red:#F87171;--amber:#FBBF24}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Inter,Roboto,sans-serif;
background:var(--bg);color:var(--text);padding:2.5rem 1.25rem;max-width:880px;margin:0 auto;
-webkit-font-smoothing:antialiased}}
.header{{text-align:center;margin-bottom:2.5rem}}
.brand{{font-size:.8rem;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin-bottom:1rem}}
h1{{font-size:1.4rem;margin-bottom:.4rem;font-weight:600}}
.url{{color:var(--muted);font-size:.9rem;word-break:break-all;margin-bottom:.25rem}}
.meta{{color:var(--muted);font-size:.8rem}}
.score-ring{{display:inline-flex;align-items:center;justify-content:center;
width:128px;height:128px;border-radius:50%;border:6px solid {color};
margin:1.5rem 0 .5rem;font-size:2.4rem;font-weight:700;color:{color}}}
.band{{font-size:1rem;font-weight:600;color:{color};letter-spacing:.04em}}
.section{{background:var(--surface);border:1px solid var(--border);border-radius:14px;
margin-bottom:1rem;overflow:hidden}}
.sec-head{{background:var(--surface2);padding:.85rem 1.25rem;font-weight:600;font-size:.92rem;
letter-spacing:.01em;border-bottom:1px solid var(--border)}}
.sec-body{{padding:1rem 1.25rem;font-family:'JetBrains Mono',ui-monospace,SFMono-Regular,Menlo,monospace;
font-size:.82rem;line-height:1.65;white-space:pre-wrap;word-break:break-word}}
.ln{{display:block}}
.c-green{{color:var(--green)}}
.c-red{{color:var(--red)}}
.c-amber{{color:var(--amber)}}
.c-accent{{color:var(--accent)}}
.footer{{text-align:center;margin-top:2rem;color:#64748b;font-size:.8rem}}
.footer a{{color:var(--accent);text-decoration:none}}
.pdf-btn{{display:inline-flex;align-items:center;gap:8px;margin-top:1.4rem;padding:.7rem 1.3rem;border-radius:10px;border:none;cursor:pointer;
background:var(--accent);color:#fff;font-size:.92rem;font-weight:600}}
.pdf-btn:hover{{filter:brightness(1.12)}}
@media print{{body{{background:#fff;color:#111}}.section{{break-inside:avoid}}.no-print{{display:none!important}}}}
</style>
</head>
<body>
<div class="header">
    <div class="brand">Visible to AI · Technical Report</div>
    <h1>GEO Technical Audit</h1>
    <div class="url">{_escape(result.url)}</div>
    <div class="meta">{_escape(status_line)} · {timestamp}</div>
    <div class="score-ring">{result.score}</div>
    <div class="band">{band_label} — {result.score}/100</div>
    <button class="pdf-btn no-print" onclick="window.print()">⬇ Save as PDF</button>
</div>
{sections_html}
<div class="footer">
    Generated by <a href="https://github.com/Tahiti18/geo-optimizer-skill">GEO Optimizer</a> · the engine behind Visible to AI
</div>
</body>
</html>"""


def _render_sections(full_text: str) -> str:
    """Split the full text report on its `===` dividers and render each section
    as a styled card. The text layout is: <intro> [=][title][=][body] repeated."""
    parts = full_text.split(_DIVIDER)
    # parts[0] is the intro banner (decorative); the real content starts after the
    # first divider as alternating title / body pairs.
    html_parts: list[str] = []
    i = 1
    while i < len(parts):
        title = parts[i].strip()
        body = parts[i + 1] if i + 1 < len(parts) else ""
        if title:
            html_parts.append(
                f'<div class="section"><div class="sec-head">{_escape(title)}</div>'
                f'<div class="sec-body">{_render_lines(body)}</div></div>'
            )
        i += 2
    return "\n".join(html_parts)


def _render_lines(body: str) -> str:
    """Render section body lines, colouring status symbols. Preserves alignment
    (progress bars, indentation) via the monospace + pre-wrap `.sec-body`."""
    out: list[str] = []
    for raw in body.split("\n"):
        if raw.strip() == "":
            continue
        cls = "ln"
        if "✅" in raw:
            cls += " c-green"
        elif "❌" in raw:
            cls += " c-red"
        elif "⚠️" in raw or "🟡" in raw or "🟠" in raw:
            cls += " c-amber"
        elif "💡" in raw:
            cls += " c-accent"
        out.append(f'<span class="{cls}">{_escape(raw)}</span>')
    return "".join(out)


def _escape(text: str) -> str:
    """Escape special HTML characters."""
    import html as _html

    return _html.escape(text, quote=True)
